# 2023-04-02 - Exploratory experiments


```{r}
experiment_slug <- "2023-04-02-psynth-small-ds"

working_directory <- paste0(
  "experiments/",
  experiment_slug,
  "/analysis/"
)
```

## Dependencies

```{r}
library(tidyverse)
library(ggplot2)
library(cowplot)
library(RColorBrewer)
library(khroma)
source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")
```

```{r}
print(version)
```

## Setup

```{r}
# Configure our default graphing theme
theme_set(theme_cowplot())
# Create a directory to store plots
plot_directory <- paste0(working_directory, "plots/")
dir.create(plot_directory, showWarnings=FALSE)
```

```{r}
summary_data_loc <- paste0(working_directory, "data/aggregate.csv")
summary_data <- read_csv(summary_data_loc)

eval_reduction_fun <- function(eval_mode, cohort_param, ds_param) {
  if (eval_mode == "cohort") {
    return(1.0 / cohort_param)
  } else if (eval_mode == "down-sample") {
    return(ds_param)
  } else if (eval_mode == "full") {
    return(1.0)
  }
}

fit_est_mode_fun <- function(est_mode) {
  if (est_mode == "ancestor-opt") {
    return("ancestor")
  } else if (est_mode == "relative-opt") {
    return("relative")
  }
  return(est_mode)
}

summary_data$evals_per_gen <- mapply(
  eval_reduction_fun,
  summary_data$EVAL_MODE,
  summary_data$NUM_COHORTS,
  summary_data$TEST_DOWNSAMPLE_RATE
)
summary_data$evals_per_gen <- as.factor(
  summary_data$evals_per_gen
)

summary_data$PROBLEM <- as.factor(
  summary_data$PROBLEM
)
summary_data$SELECTION <- as.factor(
  summary_data$SELECTION
)
summary_data$EVAL_MODE <- as.factor(
  summary_data$EVAL_MODE
)

summary_data$EVAL_FIT_EST_MODE <- mapply(
  fit_est_mode_fun,
  summary_data$EVAL_FIT_EST_MODE
)
summary_data$EVAL_FIT_EST_MODE <- factor(
  summary_data$EVAL_FIT_EST_MODE,
  levels = c(
    "none",
    "ancestor",
    "relative"
  ),
  labels = c(
    "none",
    "ancestor",
    "relative"
  )
)
summary_data$NUM_COHORTS <- as.factor(
  summary_data$NUM_COHORTS
)
summary_data$TEST_DOWNSAMPLE_RATE <- as.factor(
  summary_data$TEST_DOWNSAMPLE_RATE
)

summary_data <- summary_data %>%
  mutate(
    fit_est_mode = factor(
      paste(
        EVAL_FIT_EST_MODE, EVAL_MAX_PHYLO_SEARCH_DEPTH, sep = "-"
      ),
      levels = c(
        "none-0",
        "ancestor-0",
        "ancestor-5",
        "ancestor-10",
        "ancestor-20",
        "relative-0",
        "relative-5",
        "relative-10",
        "relative-20"
      )
    ),
    .keep = "all"
  ) %>%
  filter(
    fit_est_mode != "ancestor-0" & fit_est_mode != "relative-0"
  )
```

## Solutions

```{r}
# problem / evals_per_gen / EVAL_FIT_EST_MODE

solution_counts <- summary_data %>%
  group_by(
    PROBLEM,
    evals_per_gen,
    fit_est_mode,
    EVAL_MODE
  ) %>%
  summarize(
    solution_count = sum(found_solution == "1")
  )

plt_solutions <- function(data, problem) {
  data %>%
    filter(PROBLEM == problem) %>%
    ggplot(
      aes(
        x = fit_est_mode,
        y = solution_count,
        fill = fit_est_mode
      )
    ) +
    geom_col() +
    scale_y_continuous(
      limits = c(0, 20),
      breaks = seq(0, 20, 2),
      labels = seq(0, 20, 2)
    ) +
    facet_wrap(
      evals_per_gen ~ EVAL_MODE,
      ncol = 2
    ) +
    theme(
      legend.position = "none",
      axis.text.x = element_text(angle = 45, hjust = 1)
    )
  ggsave(
    filename = paste0(plot_directory, problem, "-final.pdf"),
    height = 15,
    width = 7
  )
}
plt_solutions(solution_counts, "grade")
plt_solutions(solution_counts, "fizz-buzz")
```

## Evaluations elapsed before solution found

```{r}
summary_data %>%
  filter(PROBLEM == "grade") %>%
  ggplot(
    aes(
      x = fit_est_mode,
      y = evaluations,
      fill = fit_est_mode
    )
  ) +
  geom_flat_violin(
    position = position_nudge(x = .2, y = 0),
    alpha = .8,
    adjust = 1.5
  ) +
  geom_point(
    mapping=aes(color = fit_est_mode),
    position = position_jitter(width = .15),
    size = .5,
    alpha = 0.8
  ) +
  geom_boxplot(
    width = .1,
    outlier.shape = NA,
    alpha = 0.5
  ) +
  facet_wrap(
    evals_per_gen ~ EVAL_MODE,
    ncol = 2
  ) +
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```
